name: Deploy to Roblox

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout data repository
        uses: actions/checkout@v4
        with:
          path: data-repo

      - name: Checkout game repository
        uses: actions/checkout@v4
        with:
          repository: Jamess-Nguyen/roblox-stock-exchange
          path: game-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rojo
        run: |
          curl -L -o rojo.zip https://github.com/rojo-rbx/rojo/releases/download/v7.6.1/rojo-7.6.1-windows-x86_64.zip
          unzip rojo.zip
          echo "$PWD" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build with Rojo
        working-directory: game-repo
        run: rojo build -o game.rbxl

      - name: Deploy to Roblox
        working-directory: game-repo
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        run: |
          rojo upload --api_key $env:ROBLOX_API_KEY --asset_id 74581969367219 --universe_id 9276760529
